### ISSUE TITLE
move inline CSS app template to an external `<link>` tag

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood-demo-adapter-netlify#10]
Currently all the CSS is in a `<style>` tag in the main _templates/app.html_
https://github.com/ProjectEvergreen/greenwood-demo-adapter-netlify/blob/main/src/templates/app.html#L12

It would be nice to move into a _styles/main.css_ and use a `<link>` tag to it instead.
```html
<link href="../styles/main.css" rel="stylesheet"></link>
```

**Comment by Bolaji06** [comment]
I can work on this, if you don't mind.

**Comment by thescientist13** [comment]
That would be great, thanks!

**Comment by Bolaji06** [comment]
> That would be great, thanks!

Sent a PR. Kindly Review
